[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "periscopic"
version = "0.1.0"
description = "SMPC builder"
readme = "README.md"
license = "MIT"
requires-python = ">=3.9"
authors = [{ name = "Alex Garza", email = "alexander.garza40@gmail.com" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/alex11garza/periscopic"
Issues = "https://github.com/alex11garza/periscopic/issues"
